# PostgreSQL. Versions 8.2 and up are supported.
development:
  adapter: postgresql
  encoding: unicode
  database: maxpoint_development
  host: localhost
  pool: 5
  username: bnelson
  password: EDSW94edsw

test:
  adapter: postgresql
  encoding: unicode
  database: maxpoint_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: maxpoint_production
  pool: 5
  username: maxpoint
  password:
